version: '2'
services:
  nginx:
    container_name: nginx
    image: whereuatngwapi/nginx
    build: 
      context: .
      dockerfile: nginx.dockerfile
    volumes:
      - ./web/dist/:/var/www/public/
    links:
        - node-1:node-1
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nodeapp-network
  node-1:
    container_name: whereuatngwapi-api
    image: whereuatngwapi/api
    build:
      context: ./api
      dockerfile: node.dockerfile
    volumes:
      - ./api/:/var/www/
    links:
      - rethinkdb:rethinkdb
    ports:
      - "3000:3000"
      - "7000:7000"
    networks:
      - nodeapp-network
    environment:
      - AUTH0_CLIENT_ID=${WHEREUAT_AUTH0_CLIENTID}
      - AUTH0_CLIENT_SECRET=${WHEREUAT_AUTH0_CLIENT_SECRET}
      - AUTH0_CLIENT_AUDIENCE=${WHEREUAT_AUTH0_CLIENT_AUDIENCE}
      - TWITTER_SECRET=${WHEREUAT_TWITTER_SECRET}
      - TWITTER_KEY=${WHEREUAT_TWITTER_KEY}
      - NODE_ENV=${NODE_ENV}

  rethinkdb:
    container_name: whereuatngwapi-rethinkdb
    image: rethinkdb:latest
    #ports:
    #  - "8080:8080"
    volumes:
      - ./data:/data
    networks:
      - nodeapp-network
networks:
  nodeapp-network:
    driver: bridge
